# Site settings
title: Johan Alexandersson 
email: johan@alexandersson.co
description: "I am Johan. I'm a Designer and Coder. I enjoy learning new things. Looking at things from a perspective that I didn’t know about before. I love doing more than making pretty pixels or coding. I want to get my feet wet and try to see the whole picture."
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: none
url: "http://me.alexandersson.co" # the base hostname & protocol for your site

linkedin_username: fossieni
twitter_username: fossieni
github_username: fossieni
resume: "https://db.tt/f3v7bBGj"

# Build settings
markdown: kramdown

keep_files: ["Gemfile", "Gemfile.lock", ".git", ".openshift"]
